package kg.restaurant.order.config;

import kg.restaurant.order.model.MenuItem;
import kg.restaurant.order.repository.MenuItemRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class MenuContentInitializer implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(MenuContentInitializer.class);

    private final MenuItemRepository menuItemRepository;

    public MenuContentInitializer(MenuItemRepository menuItemRepository) {
        this.menuItemRepository = menuItemRepository;
    }

    @Override
    public void run(String... args) {
        List<MenuItem> items = menuItemRepository.findAll();
        if (items.isEmpty()) {
            return;
        }

        int clearedCount = 0;
        for (MenuItem item : items) {
            if (clearAutoGeneratedDescription(item)) {
                menuItemRepository.save(item);
                clearedCount++;
            }
        }

        if (clearedCount > 0) {
            log.info("Cleared auto-generated menu descriptions for {} item(s)", clearedCount);
        }
    }

    private boolean clearAutoGeneratedDescription(MenuItem item) {
        boolean changed = false;
        if (isAutoGeneratedDescription(item.getDescriptionKg())) {
            item.setDescriptionKg(null);
            changed = true;
        }
        if (isAutoGeneratedDescription(item.getDescriptionRu())) {
            item.setDescriptionRu(null);
            changed = true;
        }
        if (isAutoGeneratedDescription(item.getDescription())) {
            item.setDescription(null);
            changed = true;
        }
        return changed;
    }

    private boolean isAutoGeneratedDescription(String value) {
        if (value == null || value.isBlank()) {
            return false;
        }
        String text = value.trim();
        return text.contains("категориясындагы атайын тамак")
                || text.contains("фирменное блюдо из категории")
                || text.contains("Чайхананын плову")
                || text.contains("Плов Чайханы")
                || text.contains("Сочный лагман — Чайхананын")
                || text.contains("Одно из самых любимых классических блюд")
                || text.contains("пremium тандоо")
                || text.contains("премиальный выбор");
    }
}
